version: '2'
services:

    # go:
    #     image: txapp:latest
    #     ports:
    #         - "9300:9300"
    #     links:
    #         - postgres
    #         - redis
    #     environment:
    #         TXENV: 'dev'

    postgres:
        image: onjin/alpine-postgres:9.5
        restart: unless-stopped
        ports:
            - "5432:5432"
        volumes:
            - ./files/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: txapp
            POSTGRES_PASSWORD: txapp
            POSTGRES_DB: txapp

    redis:
        image: sickp/alpine-redis:3.2.2
        restart: unless-stopped
        ports:
            - "6379:6379"

